"""Models package.

This package defines model entities that are mapped to SQL tables
configured by a third party package ``SQLAlchemy``. The package maps
each model with Object Relational Mapping to the SQL table created
by the schema defined in the ``migrations`` folder. The database
migrations are generated by the third party package
``Flask-Migration``.

Usage
-----
After creating, updating or deleting a table, run the command below
to create a new migration::

    $ flask db migrate

To create the database or update the database to a newer version, run
the following command::

    $ flask db upgrade
"""
